apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-configmap
data:
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: mern-database-secret
type: Opaque
stringData:

  MONGO_URI: "mongodb+srv://nick:17TZ7Xaino9fPQg3@clustergrud.wkf8ntf.mongodb.net/?appName=clusterGrud"